sudo: false
language: haskell
cabal: 2.4
ghc:
  - "7.0"
  - "7.2"
  - "7.4"
  - "7.6"
  - "7.8"
  - "7.10"
  - "8.0"
  - "8.2"
  - "8.4"
  - "8.6"

script:
- cabal v2-configure
- cabal v2-build
- cabal v2-test
